# config for whitelabel tuya wifi socket
# RTL8710BX (T102-V1.1; 2 MiB) with BL0937 and relay
substitutions:
  # name of the device
  device_name: wl-tuya

  # pins
  button_pin: P18 # SW1; push-button to GND
  relay_pin:  P15 # NPN to Relay; HIGH = ON; shared with LED right of SW1
  led_pin:    P5  # LED left of SW1; LOW = ON

  # BL0937 Power Monitor Pins
  ps_sel:       P14
  ps_cf:        P0
  ps_cf1:       P12

  # calibration, see https://esphome.io/components/sensor/hlw8012.html#calibration
  voltage_divider: "1526.08"
  current_resistor: "0.00181"
  current_multiply: "0.88588"

esphome:
  name: ${device_name}
  friendly_name: "Whitelabel Tuya"
  comment: "Whitelabel Tuya"


############
## Basics ##
############
rtl87xx:
  # actual hardware is 't102-v1.1', but WR2 works better and is close enough...
  board: wr2

  # TODO: BL0937 does not work in current stable, see https://github.com/libretiny-eu/libretiny/issues/155
  framework:
    version: 1.6.0

logger:
api:
  encryption:
    key: !secret api_key
ota:
  - platform: esphome
    password: !secret ota_password
wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${device_name} Fallback"
captive_portal:


################
## Web Portal ##
################
web_server:
  include_internal: True

#############
## Sensors ##
#############
sensor:
  # BL0942
  - platform: hlw8012
    model: BL0937
    sel_pin: 
      number: ${ps_sel}
      inverted: True
    cf_pin: ${ps_cf}
    cf1_pin: ${ps_cf1}
    voltage:
      name: "${device_name}.voltage"
    current:
      name: "${device_name}.current"
      filters: 
        - multiply: ${current_multiply}
    power:
      name: "${device_name}.power"
    energy:
      name: "${device_name}.energy"
    update_interval: 1s # TODO reduce to 60s if you face issues
    voltage_divider: ${voltage_divider}
    current_resistor: ${current_resistor}

  # WiFi signal strength
  - platform: wifi_signal
    id: wifi_signal_db
    #update_interval: 1s
  - platform: copy
    name: "${device_name}.wifi-signal-strength"
    internal: True
    unit_of_measurement: "%"
    source_id: wifi_signal_db
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version

binary_sensor:
  # button on the PCB
  # toggles the relay whenn pressed
  - platform: gpio
    id: push_button
    pin:
      number: ${button_pin}
      mode: INPUT_PULLUP
      inverted: True
    on_click: 
      then:
        - switch.toggle: relay

############
## Output ##
############
switch:
  - platform: gpio
    id: relay
    name: "${device_name}.relay"
    pin: 
      number: ${relay_pin}
      inverted: False

status_led:
  id: led
  pin: 
      number: ${led_pin}
      inverted: True
