# config for aubess tuya wifi socket
# BK7231N with BL0942 and relay
substitutions:
  # name of the device
  device_name: aubess-tuya

  # pins
  bl0942_tx_pin: TX1
  bl0942_rx_pin: RX1
  button_pin: P23    # push-button to GND
  sw_pin:     P24    # (external) switch to GND
  relay_pin:  P26    # NPN to Relay; HIGH = ON
  led_pin:    P8     # LOW = ON

esphome:
  name: ${device_name}
  friendly_name: "Aubess Tuya"
  comment: "Aubess Tuya"


############
## Basics ##
############
bk72xx:
  board: cb2s

logger:
api:
  encryption:
    key: !secret api_key
ota:
  password: !secret ota_password
wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${device_name} Fallback"
captive_portal:


################
## Web Portal ##
################
web_server:
  include_internal: True

#############
## Sensors ##
#############
uart:
  id: bl0942_uart
  tx_pin: ${bl0942_tx_pin}
  rx_pin: ${bl0942_rx_pin}
  baud_rate: 4800
  stop_bits: 1

sensor:
  # BL0942
  - platform: bl0942
    uart_id: bl0942_uart
    voltage: 
      name: "${device_name}.voltage"
    current: 
      name: "${device_name}.current"
    power: 
      name: "${device_name}.power"
      # BL0942 may report negative power, use this option to invert it
      filters: 
        - multiply: -1
    energy: 
      name: "${device_name}.energy"
    frequency: 
      name: "${device_name}.frequency"
    update_interval: 1s # TODO reduce to 60s if you face issues

  # WiFi signal strength
  - platform: wifi_signal
    id: wifi_signal_db
    #update_interval: 1s
  - platform: copy
    name: "${device_name}.wifi-signal-strength"
    internal: True
    unit_of_measurement: "%"
    source_id: wifi_signal_db
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);

binary_sensor:
  # button on the PCB
  # toggles the relay whenn pressed
  - platform: gpio
    id: push_button
    pin:
      number: ${button_pin}
      mode: INPUT_PULLUP
      inverted: True
    on_click: 
      then:
        - switch.toggle: relay

  # external switch
  # toggles the relay on state change
  - platform: gpio
    id: ext_switch
    pin:
      number: ${sw_pin}
      mode: INPUT_PULLUP
      inverted: True
    on_press: 
      then:
        - switch.toggle: relay
    on_release: 
      then:
        - switch.toggle: relay

############
## Output ##
############
switch:
  - platform: gpio
    id: relay
    name: "${device_name}.relay"
    pin: 
      number: ${relay_pin}
      inverted: False

status_led:
  id: led
  pin: 
      number: ${led_pin}
      inverted: True
